project:
  type: website
  output-dir: docs
  render: ["index.qmd", "learning_objectives.qmd",
  "extract_transform.qmd","about.qmd"]

website:
  title: "CS 123 Teaching Demo"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - learning_objectives.qmd
      - extract_transform.qmd
      - about.qmd
  
format:
  html:
    theme: cosmo
    css: styles.css
    include-in-header:
      - text: |
          <style>
          .custom-green-header h1 {
            color: green;
            font-size: 2em;
          }
          </style>
    toc: true

editor: visual
